language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"

before_install:
    - pip install coveralls

script:
    - nosetests -v --with-coverage --cover-package=pyhipku

after_success:
    - coveralls

notifications:
    email: false
